src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Phone_NO__c</fullName>
        <label>Bank Phone NO.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agra</fullName>
                </value>
                <value>
                    <fullName>Bikaner</fullName>
                </value>
                <value>
                    <fullName>Ghaziabad</fullName>
                </value>
                <value>
                    <fullName>Jaipur</fullName>
                </value>
                <value>
                    <fullName>Jaisalmer</fullName>
                </value>
                <value>
                    <fullName>Jodhpur</fullName>
                </value>
                <value>
                    <fullName>Kanpur</fullName>
                </value>
                <value>
                    <fullName>Lucknow</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
                <value>
                    <fullName>Nagpur</fullName>
                </value>
                <value>
                    <fullName>Nashik</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>Udaipur</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I Year</fullName>
                </value>
                <value>
                    <fullName>II Year</fullName>
                </value>
                <value>
                    <fullName>III Year</fullName>
                </value>
                <value>
                    <fullName>IV Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_No__c</fullName>
        <label>Contact No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam. Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_No__c</fullName>
        <label>Father Mobile No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fees_Summitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Summitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Donation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Donation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Landline_Number__c</fullName>
        <label>Landline Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>A+</fullName>
                </value>
                <value>
                    <fullName>A++</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Over_All_Amount__c</fullName>
        <label>Pending Over All Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS-A</fullName>
                </value>
                <value>
                    <fullName>CS-B</fullName>
                </value>
                <value>
                    <fullName>ME-A</fullName>
                </value>
                <value>
                    <fullName>ME-B</fullName>
                </value>
                <value>
                    <fullName>EC-A</fullName>
                </value>
                <value>
                    <fullName>EC-B</fullName>
                </value>
                <value>
                    <fullName>EE-A</fullName>
                </value>
                <value>
                    <fullName>EE-B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>UP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Contact_No__c</fullName>
        <label>Student Contact No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Shailendra Sharma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Registrar.cls
public class Registrar 
{
	public  Registrar() //Constructor
    {
     //*********************Teacher Layout*****************
    	 //*********************Student Personal Info*******
        Student__c student = new Student__c();
        student.Student_Name__c = 'Surendra';
        student.Roll_Number__c = 53447;
        student.Contact_No__c = '9982876350';
        student.Father_Name__c = 'Amar Nath Sharma';
        student.Father_Mobile_No__c = '3563431234';
        student.Landline_Number__c = '01413269915';
        student.Address__c = '1273,Jaipur';
        student.Email_Id__c = 's.sharma@gmail.com';        
        student.Overall_Grade__c = 'A';      
        //*************Class Info****************************
        student.Stream__c = 'ME';
        student.Class__c = 'II Year';
        student.Section__c = 'ME-A';
       //****************Fees Info**************************
        student.Current_Year__c = date.parse('2/08/2022');
        student.Exam_Fees_Submitted__c = true;
        student.Fees_Summitted__c = true; 
        student.Is_Donation__c = true;
        student.Pending_Fees_Amount__c = 24;
        student.Pending_Exam_Fees__c = 12;
        student.Donation_Amount__c = 23;
        student.Pending_Over_All_Amount__c= 10;
       //****************Bank Info**************************
        student.Bank_Name__c = 'Axis Bank';
        student.IFSC_Code__c = 'UTIB000031';
        student.Account_Number__c = 235641232;
        student.Bank_Phone_NO__c = '0141434744';
        student.Student_Contact_No__c= '9982876350';
        student.City__c = 'Jaipur';
        student.State__c = 'Rajasthan';    
        insert student;  //Insert Record**************************   
    }
}