src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Back_Subject__c</fullName>
        <label>Back Subject</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Mechanics</fullName>
                </value>
                <value>
                    <fullName>Artificial intelligence</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Engineering Physics</fullName>
                </value>
                <value>
                    <fullName>Antenna</fullName>
                </value>
                <value>
                    <fullName>Control System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I Year</fullName>
                </value>
                <value>
                    <fullName>II Year</fullName>
                </value>
                <value>
                    <fullName>III Year</fullName>
                </value>
                <value>
                    <fullName>IV Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_No__c</fullName>
        <label>Contact No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam. Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_No__c</fullName>
        <label>Father Mobile No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fees_Summitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Summitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>III_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>III Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>II_Sem_Percentage__c</fullName>
        <label>II Sem. Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IVSem_Percentage__c</fullName>
        <label>IVSem Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IV_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IV Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>I_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>I_Sem_Percentage__c</fullName>
        <label>I Sem. Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Landline_Number__c</fullName>
        <label>Landline Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>A+</fullName>
                </value>
                <value>
                    <fullName>A++</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS-A</fullName>
                </value>
                <value>
                    <fullName>CS-B</fullName>
                </value>
                <value>
                    <fullName>ME-A</fullName>
                </value>
                <value>
                    <fullName>ME-B</fullName>
                </value>
                <value>
                    <fullName>EC-A</fullName>
                </value>
                <value>
                    <fullName>EC-B</fullName>
                </value>
                <value>
                    <fullName>EE-A</fullName>
                </value>
                <value>
                    <fullName>EE-B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Shailendra Sharma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Teacher.cls
public class Teacher {
    public Teacher ()  //Constructor
    {    
     //*********************Teacher Layout*****************
     	//*********************Student Personal Info*********
        Student__c student = new Student__c();
        student.Student_Name__c = 'Ashok Kumar';
        student.Roll_Number__c = 52346;
        student.Contact_No__c = '9982876356';
        student.Father_Name__c = 'Suresh Sharma';
        student.Father_Mobile_No__c= '3563431234';
        student.Landline_Number__c = '01413269916';
        student.Address__c = '1117,Jaipur';
        student.Email_Id__c = 's.sharma@gmail.com';
        student.Overall_Grade__c = 'A';
        //*************Class Info****************************
        student.Stream__c = 'CS';
        student.Class__c = 'II Year';
        student.Section__c = 'CS-B';
        //****************Fees Info**************************
        student.Current_Year__c = date.parse('12/08/2022');
        student.Pending_Fees_Amount__c = 04;
        student.Pending_Exam_Fees__c = 12;
        student.Exam_Fees_Submitted__c = true;
        student.Fees_Summitted__c = true;
        //*****************Semester Details*******************
        student.I_Sem_Back__c = true;
        student.I_Sem_Percentage__c = 79;
        student.II_Sem_Percentage__c = 80;
        student.IVSem_Percentage__c =79;
        student.III_Sem_Back__c = true;
        student.IV_Sem_Back__c = true;
        student.Back_Subject__c ='DE;EDC'; 
        insert student;   // Insert Record**************************
        System.debug('Record Id of this Record:'+ student.id);  //Get Record Id
    }

}