src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Back_Subject__c</fullName>
        <label>Back Subject</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>DSA</fullName>
                </value>
                <value>
                    <fullName>Mechanics</fullName>
                </value>
                <value>
                    <fullName>Artificial intelligence</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Engineering Physics</fullName>
                </value>
                <value>
                    <fullName>Antenna</fullName>
                </value>
                <value>
                    <fullName>Control System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I Year</fullName>
                </value>
                <value>
                    <fullName>II Year</fullName>
                </value>
                <value>
                    <fullName>III Year</fullName>
                </value>
                <value>
                    <fullName>IV Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_No__c</fullName>
        <label>Contact No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam. Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_No__c</fullName>
        <label>Father Mobile No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fees_Summitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Summitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>I_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>I_Sem_Percentage__c</fullName>
        <label>I Sem. Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>A+</fullName>
                </value>
                <value>
                    <fullName>A++</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS-A</fullName>
                </value>
                <value>
                    <fullName>CS-B</fullName>
                </value>
                <value>
                    <fullName>ME-A</fullName>
                </value>
                <value>
                    <fullName>ME-B</fullName>
                </value>
                <value>
                    <fullName>EC-A</fullName>
                </value>
                <value>
                    <fullName>EC-B</fullName>
                </value>
                <value>
                    <fullName>EE-A</fullName>
                </value>
                <value>
                    <fullName>EE-B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Shailendra Sharma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentQuery.cls
public class StudentQuery
{
	public StudentQuery()
    {   
    /*{
		//Get Student Query of one Record.
		Student__c student = new Student__c();
    	student = [Select id,Name,Student_Name__c,Roll_Number__c, Contact_No__c,Father_Name__c,Father_Mobile_No__c,Email_Id__c,Overall_Grade__c,Stream__c,Class__c,Section__c,Current_Year__c,Pending_Fees_Amount__c, Pending_Exam_Fees__c,Exam_Fees_Submitted__c,Fees_Summitted__c,I_Sem_Back__c,I_Sem_Percentage__c,Back_Subject__c from Student__c limit 1];
        System.debug(student);  
    }*/  
        //Get Student Query of 5 Record.
        List<Student__c> students = new List<Student__c>();
    	students = [Select Id,Name,Student_Name__c,Roll_Number__c,Contact_No__c from Student__c];
    	for(Student__c s:student)
    	{
        	System.debug('Record of Student:'+ s);    
   	    }
    }
}